### PR TITLE
Bump K3s dependecies to 1.29.9

### PR DESCRIPTION
**Pull request by dereknola**
## Changes
- Bring K3s dependencies from 1.29.3 to 1.31.1
- Bump go dependencies for minor CVEs

## Linked Issues:
https://github.com/rancher/rke2/issues/6913
https://github.com/rancherlabs/image-scanning/issues/3943

### CODE REVIEW

**Review by brandond — CHANGES_REQUESTED** [review]
This will break how we use the modsync script at https://github.com/rancher/image-build-rke2-cloud-provider/blob/main/scripts/modsync.sh to allow building against different versions of Kubernetes. The script only works if the module versions for the target Kubernetes are **newer** than what's in go.mod. If we update the checked in go.mod to v1.31 then we will be unable to tag builds for any release older than that.

Either leave it on an older Kubernetes version, or fix the version check in that script to update the module version if it's not equal, instead of newer.

**Comment by dereknola** [comment]
How are we building for v1.28 releases if the existing release is on 1.29.3?

**Comment by brandond** [comment]
https://github.com/rancher/image-build-rke2-cloud-provider/tree/release-v1.28 lol

**Comment by dereknola** [comment]
Ah okay... so I will bump only to 1.29.9

**Comment by brandond** [comment]
Yeah it doesn't matter a TON since all the modules get upgraded to the Kubernetes version specified in the tag anyway.

**Review by brandond — APPROVED** [review]

**Review by VestigeJ — APPROVED** [review]

**Review by briandowns — APPROVED** [review]

**Pull request merged**
